# Generated by Django 3.2.5 on 2021-09-08 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bling', '0009_auto_20210908_1918'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_on', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('friend_requests', models.ManyToManyField(blank=True, default=None, related_name='_userprofile_userprofile_friend_requests_+', to='userprofile.UserProfile', verbose_name='Подписчики')),
                ('friends', models.ManyToManyField(blank=True, default=None, related_name='_userprofile_userprofile_friends_+', to='userprofile.UserProfile', verbose_name='Друзья')),
                ('profile_image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bling.blingimage', verbose_name='Фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
