# Generated by Django 3.2.5 on 2021-09-08 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, default=None, related_name='Подписчик', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='Друг', to=settings.AUTH_USER_MODEL, verbose_name='Друзья'),
        ),
    ]
