# Generated by Django 3.2.5 on 2021-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210908_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Ава'),
        ),
    ]
