# Generated by Django 3.2.5 on 2021-09-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('born_on', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('friend_requests', models.ManyToManyField(related_name='_bling_blinguser_friend_requests_+', to='bling.BlingUser')),
                ('friends', models.ManyToManyField(related_name='_bling_blinguser_friends_+', to='bling.BlingUser')),
                ('profile_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bling.blingimage')),
            ],
        ),
        migrations.CreateModel(
            name='BlingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='bling.blinguser')),
                ('images', models.ManyToManyField(to='bling.BlingImage')),
                ('liked_by', models.ManyToManyField(to='bling.BlingUser')),
            ],
        ),
        migrations.AddField(
            model_name='blingimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bling.blinguser'),
        ),
        migrations.CreateModel(
            name='BlingComment',
            fields=[
                ('blingpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bling.blingpost')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='bling.blingpost')),
            ],
            bases=('bling.blingpost',),
        ),
    ]
