# Generated by Django 3.2.5 on 2021-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blingcomment',
            name='likes_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blingpost',
            name='likes_amount',
            field=models.IntegerField(default=0),
        ),
    ]
