# Generated by Django 3.2.5 on 2021-09-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blingpost',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='bling.BlingImage'),
        ),
        migrations.AlterField(
            model_name='blingpost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, to='bling.BlingUser'),
        ),
        migrations.AlterField(
            model_name='blingpost',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blinguser',
            name='born_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blinguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blinguser',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_bling_blinguser_friend_requests_+', to='bling.BlingUser'),
        ),
        migrations.AlterField(
            model_name='blinguser',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_bling_blinguser_friends_+', to='bling.BlingUser'),
        ),
        migrations.AlterField(
            model_name='blinguser',
            name='profile_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bling.blingimage'),
        ),
    ]
