# Generated by Django 3.2.5 on 2021-09-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blingpost',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bling.userprofile', verbose_name='Автор'),
        ),
    ]
