# Generated by Django 3.2.5 on 2021-09-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0002_alter_blingpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blingimage',
            name='owner',
        ),
        migrations.AlterField(
            model_name='blingpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bling.userprofile', verbose_name='Автор'),
        ),
    ]
