# Generated by Django 3.2.5 on 2021-09-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0002_auto_20210930_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='blingpost',
            name='comments_amount',
            field=models.IntegerField(default=0),
        ),
    ]
