# Generated by Django 3.2.5 on 2021-09-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0003_blingpost_comments_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, default=None, to='bling.BlingPost', verbose_name='Понравившиеся посты'),
        ),
    ]
