# Generated by Django 3.2.5 on 2021-09-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0005_auto_20210906_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blingpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='bling.blinguser', verbose_name='Автор'),
        ),
    ]
