# Generated by Django 3.2.5 on 2021-10-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0006_blingnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blingnotification',
            old_name='reciever',
            new_name='target_user',
        ),
        migrations.RemoveField(
            model_name='blingnotification',
            name='is_seen',
        ),
    ]
