# Generated by Django 3.2.5 on 2021-10-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0007_auto_20211009_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_amount',
            field=models.IntegerField(default=0),
        ),
    ]
