# Generated by Django 3.2.5 on 2021-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0008_auto_20210907_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blinguser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='blinguser',
            name='password',
        ),
        migrations.AlterField(
            model_name='blinguser',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='Никнейм'),
        ),
    ]
