# Generated by Django 3.2.5 on 2021-10-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0008_profile_notifications_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blingnotification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='blingnotification',
            name='related_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bling.blingpost'),
        ),
    ]
