# Generated by Django 3.2.5 on 2021-09-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofile_profile_image'),
        ('bling', '0009_auto_20210908_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blingimage',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='blingpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='userprofile.userprofile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blingpost',
            name='liked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='Понравилось'),
        ),
        migrations.DeleteModel(
            name='BlingUser',
        ),
    ]
