# Generated by Django 3.2.5 on 2021-09-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0009_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blingimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
    ]
