# Generated by Django 3.2.5 on 2021-09-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0010_alter_blingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blingpost',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bling.blingimage', verbose_name='Изображения'),
        ),
    ]
