# Generated by Django 3.2.5 on 2021-10-09 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0010_auto_20211009_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blingnotification',
            options={'ordering': ['-created_on'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='blingnotification',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
