# Generated by Django 3.2.5 on 2021-10-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0011_auto_20211009_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
    ]
