# Generated by Django 3.2.5 on 2021-09-22 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bling', '0011_alter_blingpost_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blingimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='blingpost',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bling.blingimage', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='blingpost',
            name='liked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Понравилось'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bling.blingimage', verbose_name='Ава'),
        ),
    ]
