# Generated by Django 3.2.5 on 2021-09-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0012_auto_20210923_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='friend_requests',
            new_name='subscribers',
        ),
    ]
