# Generated by Django 3.2.5 on 2021-09-24 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bling', '0013_rename_friend_requests_userprofile_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
