# Generated by Django 3.2.5 on 2021-09-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0014_auto_20210924_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
